#workspace(name = "Workspace Name")

new_http_archive(
  name = "yamlcpp",
  build_file = "yamlcpp.BUILD",
  url = "https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.tar.gz",
  strip_prefix = "yaml-cpp-yaml-cpp-0.6.2",
)