#workspace(name = "org_tensorflow")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

#new_git_repository(
#    name = "yaml-cpp",
#    remote = "https://github.com/jbeder/yaml-cpp.git",
#    tag = "yaml-cpp-0.6.2",
#    build_file_content = """
#cc_library(
#    name = "yaml-cpplib",
#    srcs = glob(["src/*.h", "include/yaml-cpp/*.h", "src/*.cpp", "src/contrib/*"]),
#    hdrs = glob(["include/yaml-cpp/*.h", "include/yaml-cpp/contrib/*.h", "include/yaml-cpp/node/*.h", "include/yaml-cpp/node/detail/*.h"]),
#    visibility = ["//visibility:public"]
#)""",
#)

new_http_archive(
  name = "yamlcpp",
  build_file = "yamlcpp.BUILD",
  url = "https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.tar.gz",
  strip_prefix = "yaml-cpp-yaml-cpp-0.6.2",
)