cc_library(
    name = "yaml-cpp",
    srcs = glob(["yaml-cpp_repo/src/**/*", "yaml-cpp_repo/include/**/*"]),
    hdrs = glob(["yaml-cpp_repo/include/**/*"]),
    visibility = ["//visibility:public"],
)